// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSMeFe_eeBQqcagC5wrN-mlnRr86BxUO0',
    appId: '1:417156774528:web:83e6c9b2f8b108f2cc0465',
    messagingSenderId: '417156774528',
    projectId: 'the-formula-310013',
    authDomain: 'the-formula-310013.firebaseapp.com',
    storageBucket: 'the-formula-310013.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbkiR4miNSwKIc38YFbaDAWbgI7s2-AEA',
    appId: '1:417156774528:android:86910eceac56eb5ecc0465',
    messagingSenderId: '417156774528',
    projectId: 'the-formula-310013',
    storageBucket: 'the-formula-310013.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRTrKSzDNZOGWc21gZYbL_1sGak6Z7FAM',
    appId: '1:417156774528:ios:c40d73d97ebef7a2cc0465',
    messagingSenderId: '417156774528',
    projectId: 'the-formula-310013',
    storageBucket: 'the-formula-310013.appspot.com',
    androidClientId: '417156774528-8ukvd0h9nf1uhvt1clbiin3g8k03kmac.apps.googleusercontent.com',
    iosClientId: '417156774528-ilssrhsogpsv71bc0hs5olr3iqfjufed.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieTicketApp',
  );
}
